# AMOSTRAGEM

In [1]:
import pandas as pd
import numpy as np
import random

In [3]:
data = pd.read_csv(r"S:\gits_stella\Python\estatistica_python\census.csv")

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   final-weight    32561 non-null  int64 
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64 
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64 
 11  capital-loos    32561 non-null  int64 
 12  hour-per-week   32561 non-null  int64 
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [6]:
data.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

## Amostragem aleatória simples

In [14]:
df_amostra = data.sample(n=100, random_state = 1)
df_amostra.shape

(100, 15)

In [13]:
df_amostra.head()

age          workclass  final-weight   education  education-num  \
9646    62   Self-emp-not-inc         26911     7th-8th              4   
709     18            Private        208103        11th              7   
7385    25            Private        102476   Bachelors             13   
16671   33            Private        511517     HS-grad              9   
21932   36            Private        292570        11th              7   

            marital-status          occupation     relationship    race  \
9646               Widowed       Other-service    Not-in-family   White   
709          Never-married       Other-service   Other-relative   White   
7385         Never-married     Farming-fishing        Own-child   White   
16671   Married-civ-spouse      Prof-specialty          Husband   White   
21932        Never-married   Machine-op-inspct        Unmarried   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
9646    Female             0             0             66   United-States   
709       Male             0             0             25   United-States   
7385      Male         27828             0             50   United-States   
16671     Male             0             0             40   United-States   
21932   Female             0             0             40   United-States   

       income  
9646    <=50K  
709     <=50K  
7385     >50K  
16671   <=50K  
21932   <=50K

In [24]:
def amostragem_ale_simples (dataset, amostras):
    return data.sample(n = amostras, random_state=1)

In [26]:
df_amostra_simples = amostragem_ale_simples(data,100)
df_amostra_simples.shape

(100, 15)

In [27]:
df_amostra_simples.head()

age          workclass  final-weight   education  education-num  \
9646    62   Self-emp-not-inc         26911     7th-8th              4   
709     18            Private        208103        11th              7   
7385    25            Private        102476   Bachelors             13   
16671   33            Private        511517     HS-grad              9   
21932   36            Private        292570        11th              7   

            marital-status          occupation     relationship    race  \
9646               Widowed       Other-service    Not-in-family   White   
709          Never-married       Other-service   Other-relative   White   
7385         Never-married     Farming-fishing        Own-child   White   
16671   Married-civ-spouse      Prof-specialty          Husband   White   
21932        Never-married   Machine-op-inspct        Unmarried   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
9646    Female             0             0             66   United-States   
709       Male             0             0             25   United-States   
7385      Male         27828             0             50   United-States   
16671     Male             0             0             40   United-States   
21932   Female             0             0             40   United-States   

       income  
9646    <=50K  
709     <=50K  
7385     >50K  
16671   <=50K  
21932   <=50K

## Amostragem sistemática


In [47]:
df_amostra_sist = len(data) // 100
df_amostra_sist

325

In [46]:
np.arange(68,len(data),step = 325)

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [50]:
def amostragem_sistematica (dataset, amostras):
    intervalo = len(dataset) // amostras
    random.seed(1)
    inicio = random.randint(0, intervalo)
    indices = np.arange(inico, len(data), step = intervalo)
    amostra_sistematica = data.iloc[indices]
    return amostra_sistematica

## Amostragem por grupos

In [52]:
len(data) // 10

3256

In [53]:
grupos = []
id_grupo = 0
cont = 0
for _ in data.iterrows():
    grupos.append(id_grupo)
    cont += 1
    if cont > 3256:
        cont = 0
        id_grupo += 1

In [58]:
np.unique(grupos, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248],
       dtype=int64))

In [61]:
np.shape(grupos)

(32561,)

In [63]:
data['grupo'] = grupos
data.head(-1)

age          workclass  final-weight      education  education-num  \
0       39          State-gov         77516      Bachelors             13   
1       50   Self-emp-not-inc         83311      Bachelors             13   
2       38            Private        215646        HS-grad              9   
3       53            Private        234721           11th              7   
4       28            Private        338409      Bachelors             13   
...    ...                ...           ...            ...            ...   
32555   22            Private        310152   Some-college             10   
32556   27            Private        257302     Assoc-acdm             12   
32557   40            Private        154374        HS-grad              9   
32558   58            Private        151910        HS-grad              9   
32559   22            Private        201490        HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32555        Never-married     Protective-serv   Not-in-family   White   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
0         Male          2174             0             40   United-States   
1         Male             0             0             13   United-States   
2         Male             0             0             40   United-States   
3         Male             0             0             40   United-States   
4       Female             0             0             40            Cuba   
...        ...           ...           ...            ...             ...   
32555     Male             0             0             40   United-States   
32556   Female             0             0             38   United-States   
32557     Male             0             0             40   United-States   
32558   Female             0             0             40   United-States   
32559     Male             0             0             20   United-States   

       income  grupo  
0       <=50K      0  
1       <=50K      0  
2       <=50K      0  
3       <=50K      0  
4       <=50K      0  
...       ...    ...  
32555   <=50K      9  
32556   <=50K      9  
32557    >50K      9  
32558   <=50K      9  
32559   <=50K      9  

[32560 rows x 16 columns]

In [69]:
random.randint(0, 9)

7

In [78]:
df_agrupamento = data[data['grupo'] == 7]
df_agrupamento.shape

(3257, 16)

In [79]:
df_agrupamento['grupo'].value_counts()

7    3257
Name: grupo, dtype: int64

## Amostragem estratificada